# This workflow builds and uploads the MOBSTERm Python package using Twine

name: Upload Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install build twine

    - name: Build package
      run: |
        python3 -m build

    - name: Check package
      run: |
        python3 -m twine check dist/*

    - name: Publish package to TestPyPI
      run: |
        python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}

    - name: Publish package to PyPI
      run: |
        python3 -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
